name: Verify
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      staging:
        required: false
        default: false
        type: boolean
    secrets:
      opensource-repository-username:
        required: false
      opensource-repository-password:
        required: false
      commercial-repository-username:
        required: false
      commercial-repository-password:
        required: false
      google-chat-webhook-url:
        required: true
      token:
        required: true
jobs:
  verify:
    name: Verify
    runs-on: ${{ vars.UBUNTU_SMALL || 'ubuntu-latest' }}
    steps:
      - name: Check Out Release Verification Tests
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-boot-release-verification
          ref: 'v0.0.6'
          token: ${{ secrets.token }}
      - name: Check Out Send Notification Action
        uses: actions/checkout@v4
        with:
          path: send-notification
          sparse-checkout: .github/actions/send-notification
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 17
      - name: Set Up Homebrew
        if: ${{ !vars.COMMERCIAL }}
        uses: Homebrew/actions/setup-homebrew@7657c9512f50e1c35b640971116425935bab3eea
      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          cache-read-only: false
      - name: Configure Gradle Properties
        shell: bash
        run: |
          mkdir -p $HOME/.gradle
          echo 'org.gradle.daemon=false' >> $HOME/.gradle/gradle.properties
      - name: Run Release Verification Tests
        env:
          RVT_VERSION: ${{ inputs.version }}
          RVT_RELEASE_TYPE: ${{ vars.COMMERCIAL && 'commercial' || 'oss' }}
          RVT_STAGING: ${{ inputs.staging }}
          RVT_OSS_REPOSITORY_USERNAME: ${{ secrets.opensource-repository-username }}
          RVT_OSS_REPOSITORY_PASSWORD: ${{ secrets.opensource-repository-password }}
          RVT_COMMERCIAL_REPOSITORY_USERNAME: ${{ secrets.commercial-repository-username }}
          RVT_COMMERCIAL_REPOSITORY_PASSWORD: ${{ secrets.commercial-repository-password }}
        run: ./gradlew spring-boot-release-verification-tests:test
      - name: Upload Build Reports on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-reports
          path: '**/build/reports/'
      - name: Send Notification
        uses: ./send-notification/.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.google-chat-webhook-url }}
          status: ${{ job.status }}
          run-name: ${{ format('{0} | Verification | {1}', github.ref_name, inputs.version) }}
